apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: demo-application
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/thisthat/progressiveDelivery-masterclass.git'
    targetRevision: rollout-test
    path: "gitops/manifests/demo-application"
  destination:
    namespace: demo
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
