apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: load-test
  namespace: demo
spec:
  container:
    name: testy-test
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 30'

# spec:
#   container:
#     name: testy-test
#     image: grafana/k6:0.45.0
#     command:
#       - 'run'
#       - 'https://raw.githubusercontent.com/thisthat/progressiveDelivery-masterclass/add-post-test/gitops/manifests/demo-application/load.js'
