apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: load-test
spec:
  container:
    name: testy-test
    image: grafana/k6:0.45.0
    command:
      - 'run'
      - 'https://raw.githubusercontent.com/li-clutter-org/k6-circleci-example/master/loadtests/performance-test.js'
