apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: load-test
  namespace: demo
spec:
  container:
    name: testy-test
    image: grafana/k6:0.45.0
    command:
      - 'K6_PROMETHEUS_REMOTE_URL=http://prometheus-k8s.monitoring:9090/api/v1/write'
      - 'k6'
      - 'run'
      - 'https://raw.githubusercontent.com/thisthat/progressiveDelivery-masterclass/f612ee6/gitops/manifests/demo-application/load.js'
