kind: Namespace
apiVersion: v1
metadata:
  name: roll-demo
  labels:
    name: demo
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetricsProvider
metadata:
  name: my-provider
  namespace: roll-demo
spec:
  type: prometheus
  targetServer: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
---
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetric
metadata:
  name: keptnmetric-sample
  namespace: roll-demo
spec:
  provider:
    name: my-provider
  query: 'avg(rate(container_cpu_cfs_throttled_seconds_total{container="server", namespace="roll-demo"}[1m]))'
  fetchIntervalSeconds: 5
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: roll-demo
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    count: 1
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring:9090
        query: >+
          sum(machine_cpu_cores)
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  namespace: roll-demo
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: roll-demo
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - analysis:
          templates:
          - templateName: success-rate
          args:
          - name: ingress
            value: canary-demo
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
        app.kubernetes.io/part-of: demorollout
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---