kind: Namespace
apiVersion: v1
metadata:
  name: roll-demo
  labels:
    name: demo
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetricsProvider
metadata:
  name: my-provider
  namespace: roll-demo
spec:
  type: prometheus
  targetServer: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
---
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetric
metadata:
  name: keptnmetric-sample
  namespace: roll-demo
spec:
  provider:
    name: my-provider
  query: 'avg(rate(container_cpu_cfs_throttled_seconds_total{container="server", namespace="roll-demo"}[1m]))'
  fetchIntervalSeconds: 5
---

---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  namespace: roll-demo
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---

---